function colorTheme() {
	return {
		__html:
			"<span style='color: var(--codetheme-gray)'>// With a checkbox with onClick with this handle (+ CSS configurate how this project)</span><br /><span style='color: var(--codetheme-blue-dark)'>const</span> <span style='color: var(--codetheme-yellow-soft)'>handleColorTheme</span> <span style='color: var(--codetheme-live)'>=</span> <span style='color: var(--codetheme-blue)'>event</span> <span style='color: var(--codetheme-blue-dark)'>=></span> <span style='color: var(--codetheme-pink)'>{</span><br /> <span style='color: var(--codetheme-blue)'>event</span><span style='color: var(--codetheme-live)'>.</span><span style='color: var(--codetheme-blue)'>target</span><span style='color: var(--codetheme-live)'>.</span><span style='color: var(--codetheme-blue)'>checked</span><br />  <span style='color: var(--codetheme-live)'>?</span> <span style='color: var(--codetheme-blue)'>document</span><span style='color: var(--codetheme-live)'>.</span><span style='color: var(--codetheme-blue-dark)'>documentElement</span><span style='color: var(--codetheme-live)'>.</span><span style='color: var(--codetheme-yellow-soft)'>setAttribute</span><span style='color: var(--codetheme-blue)'>(</span><span style='color: var(--codetheme-brown)'>'data-theme'</span><span style='color: var(--codetheme-live)'>,</span> <span style='color: var(--codetheme-brown)'>'dark'</span><span style='color: var(--codetheme-blue)'>)</span><br />  <span style='color: var(--codetheme-live)'>:</span> <span style='color: var(--codetheme-blue)'>document</span><span style='color: var(--codetheme-live)'>.</span><span style='color: var(--codetheme-blue-dark)'>documentElement</span><span style='color: var(--codetheme-live)'>.</span><span style='color: var(--codetheme-yellow-soft)'>setAttribute</span><span style='color: var(--codetheme-blue)'>(</span><span style='color: var(--codetheme-brown)'>'data-theme'</span><span style='color: var(--codetheme-live)'>,</span> <span style='color: var(--codetheme-brown)'>'light'</span><span style='color: var(--codetheme-blue)'>)</span><span style='color: var(--codetheme-live)'>;</span><br /><span style='color: var(--codetheme-pink)'>}</span><span style='color: var(--codetheme-live)'>;</span>",
	};
}

function palette() {
	return {
		__html:
			"<span style='color: var(--codetheme-gray)'>// theme is the material ui object</span><br /><span style='color: var(--codetheme-live)'><</span><span style='color: var(--codetheme-green)'>MuiThemeProvider</span> <span style='color: var(--codetheme-blue)'>theme</span><span style='color: var(--codetheme-live)'>=</span><span style='color: var(--codetheme-blue)'>{</span><span style='color: var(--codetheme-yellow-soft)'>createMuiTheme</span><span style='color: var(--codetheme-yellow)'>(</span><span style='color: var(--codetheme-blue-dark)'>theme</span><span style='color: var(--codetheme-yellow)'>)</span><span style='color: var(--codetheme-blue)'>}</span><span style='color: var(--codetheme-live)'>></span><br /> <span style='color: var(--codetheme-gray)'>// App...</span><br /><span style='color: var(--codetheme-live)'><</span><span style='color: var(--codetheme-live)'>/</span><span style='color: var(--codetheme-green)'>MuiThemeProvider</span><span style='color: var(--codetheme-live)'>></span><br /><br />",
	};
}


export default { colorTheme, palette };
