const defaultTheme = {
	palette: {
		primary: {
			light: '#eb898d',
			main: '#d6333c',
			dark: '#78191e',
			contrastText: '#ffffff',
		},
		secondary: {
			light: '#01263c',
			main: '#004a70',
			dark: '#7594aa',
			contrastText: '#ffffff',
		},
	},
	typography: {
		htmlFontSize: 16,
		fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
		fontSize: 14,
		fontWeightLight: 300,
		fontWeightRegular: 400,
		fontWeightMedium: 500,
		fontWeightBold: 700,
		h1: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 300,
			fontSize: '3rem',
			lineHeight: 1.167,
			letterSpacing: '-0.01562em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		h2: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 300,
			fontSize: '2.75rem',
			lineHeight: 1.2,
			letterSpacing: '-0.00833em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		h3: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 400,
			fontSize: '2.35rem',
			lineHeight: 1.167,
			letterSpacing: '0em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		h4: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 400,
			fontSize: '1.90rem',
			lineHeight: 1.235,
			letterSpacing: '0.00735em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		h5: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 400,
			fontSize: '1.5rem',
			lineHeight: 1.334,
			letterSpacing: '0em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		h6: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 500,
			fontSize: '1.25rem',
			lineHeight: 1.6,
			letterSpacing: '0.0075em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		subtitle1: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 400,
			fontSize: '1rem',
			lineHeight: 1.75,
			letterSpacing: '0.00938em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		subtitle2: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 500,
			fontSize: '0.875rem',
			lineHeight: 1.57,
			letterSpacing: '0.00714em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		body1: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 400,
			fontSize: '1rem',
			lineHeight: 1.5,
			letterSpacing: '0.00938em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'none',
		},
		body2: {
			fontFamily: 'Verdana, Geneva, Tahoma, sans-serif',
			fontWeight: 400,
			fontSize: '0.875rem',
			lineHeight: 1.43,
			letterSpacing: '0.01071em',
			color: 'var(--color-text)',
			fontStyle: 'normal',
			textTransform: 'none',
		},
	},
};

export default defaultTheme;
